# My Excersise Notes #

## Load Data from a file ##

This exercise is about calculating basic statistical measures. In order to do that, we first need some data. We also need to install the libraries that will help us do the math needed for calculating the statistical measures.

In [4]:
import pandas as pd # to import data into a datadrame
import numpy as np # to set a global random seed for taking our samples
import statistics # to calculate mean and standard deviation

In [10]:
## First, use pd.read_Csv() to read the deata in "spend_n_save.txt"
spend_n_save_df = pd.read_csv("/Users/albertadlersson/Desktop/Mina Skrivbordsfiler/4. Utbilding/5. Python Learning - 2026/StatQuest Exercises/My Attempts/Ch_01 - 29 jul/spend_n_save.txt", sep='\t')

## Verify that pd.read_csv() was successful by printing out the
## first few rows with the head() function
spend_n_save_df.head()

   id  num.apples
0   1          27
1   2          17
2   3          22
3   4          23
4   5          22

In [11]:
## rename num-apples to num_apples so it's easier to access the values
spend_n_save_df.rename(columns={'num.apples': 'num_apples'}, inplace=True)

## print out first few rows to verify the rename
spend_n_save_df.head()

   id  num_apples
0   1          27
1   2          17
2   3          22
3   4          23
4   5          22

Now that we have the first few rows of the data, let's see how many rows there are, totale with the `len()` function

In [19]:
spend_n_save_df.length = len(spend_n_save_df)
print("Number of rows in spend_n_save_df:", spend_n_save_df.length)

Number of rows in spend_n_save_df: 5123

Now let's use all the data o calculate the **Population Mean** and the **Population Standard Deviation**.

## Calculate the Pupulation Mean and Populaiton Standard Deviation ##

Now that we have the data, we can calculate the **Population Mean** of the number of apples for sale at each store with the `mean()`function, which is part of the `statistics`module.

**Note:** The equation for the **Population Mean** is the same as the equation for the **Estimated Mean**, the only differnece is that for the **Population Mean** we use data from the entire population and for the **Estimated Mean** we only use a subset of the data.

In [14]:
## Calculate the mean of the number of apples for sale
## because we are using the data from every single store
## we are calculating the Population Mean.
## Anyway, we'll save the value in a variable called pop_mean

pop_mean = statistics.mean(spend_n_save_df.num_apples)

## print out the population mean
pop_mean

19.92309193831739

Since the **Population Mean** has so many digits after the decimal point, it's quite a mouthful. Try rounding the number instead, using the function `round()`.

In [15]:
round(pop_mean, ndigits=1)

19.9

Now let's calculate the  **Population Standard Deviation**. We can do that with the `pstdev()`function, which is also part of the `statistics`module.

In [16]:
## calculate the population standard deviation and save it
## in a variable called pop_sd
pop_sd = statistics.pstdev(spend_n_save_df.num_apples)

## print out the population standard deviation
pop_sd

5.038359554122998

In [36]:
pop_sum_man = sum((spend_n_save_df.num_apples - pop_mean) ** 2)
pop_var_man = pop_sum_man / spend_n_save_df.length

print("Population Variance, manual:", round(pop_var_man, ndigits=1), "\n")

pop_sd_man = pop_var_man ** 0.5

print("Population standard deviation, automatic:", 
      round(pop_sd, ndigits=1),
      "\n",
      "Population standard deviation, manual:",
      round(pop_sd_man, ndigits=1))

Population Variance, manual: 25.4

Population standard deviation, automatic: 5.0
 Population standard deviation, manual: 5.0

## Calculate the Estimated Mean and the Estimated Standard Deviation with a randomly selected subset of the data ##

Now that we know how to calculate the **Population Mean** and the **Population Standard Deviation**, let's learn how to calculate an **Estimated Mean** and an **Estimated Standard Deviation**.

The first thing we'll do is randomly select 5 values from the dataset. Specifically, we want to randomly select 5 values representing the number of apples for sale at a store.

In [37]:
## Set seed for reproducibiility
np.random.seed(42)

## Select a random sample of size 5 without replacement
rand_sample = spend_n_save_df.num_apples.sample(n=5)

## print out the 5 values in rand_sample
rand_sample

530     11
1729    15
1010    19
1149    18
1383    25
Name: num_apples, dtype: int64

Now, let's calculate the estiamted mean, just like before.

In [38]:
## calculate the estimated mean
estimated_mean = statistics.mean(rand_sample)

## print out the estimated mean
estimated_mean

17.6

To calculate the estimated standard deviation, we can use the `stdev()`function that is part of the `statistics` module

In [41]:
## Now calculate the estimated standard deviation
estimated_sd = statistics.stdev(rand_sample)
round(estimated_sd, ndigits=1)

5.2

Now let's get a sense for why the **Population Standard Deviation** is calculated with a slightly different formula than the **Estimated Standard Deviation**. First, remember the equation for the **Population Standard Deviation**. Let's compare it to the formula for the **Estimated Standard Deviation**.

\begin{array}{cc}
\text{Population Standard Deviation}
&
\text{Estimated Standard Deviation}
\\[1em]
\displaystyle \sqrt{\frac{\sum (x-\mu)^2}{N}}
&
\displaystyle \sqrt{\frac{\sum (x-\bar{x})^2}{n-1}}
\end{array}

Other than replacing the **Population Mean**, $\mu$, with the **Estimated Mean** $\bar{x}$, the big difference is the denominator. The **Population Standard Deviation** has $N$, the total number of measurements in the population, and the **Estimated Standard Deviation** has $n-1$, where $n$, is the number of measurements in the sample.

The reason the denominators are different is, int theory, because dividing by $n$ is the **Estimated Standard Deviation** will, on averafe, result in an underestimate of the **Population Standard Deviation**, and dividing by $n-1$ corrects for this bias.

So, let's see if this theory is actually true. We'll do this by selecting a bunch of samples, each with 5 randomly selected measurements and calculate the Standard Deviation both ways - using $n$ in the denominator and using $n-1$ in the denominator.

In [49]:
# Set seed for reproducibility
np.random.seed(42)

max_samples = 1000 # this is how many times we'll get a sample of random values.

## we'll save all of the estimated standard deviations in these vectors.
estimated_sds_with_n_minus_1 = [0] * max_samples
estimated_sds_with_n         = [0] * max_samples

## Here's a loop where we'll randomly select a sample
## of 5 measurements and then calculate the SD two ways
for i in range(max_samples):

    ## get a sample of random values...
    rand_sample = spend_n_save_df.num_apples.sample(n=5)

    ## SD with n-1 (estimated)
    estimated_sds_with_n_minus_1[i] = statistics.stdev(rand_sample)

    ## SD witn n
    estimated_sds_with_n[i] = statistics.pstdev(rand_sample)

Now let's calculate and print the average SD that we just calculated for both equations...

In [51]:
print("Average SD with n-1:", round(sum(estimated_sds_with_n_minus_1) / max_samples, 1))
print("Average SD with n:", round(sum(estimated_sds_with_n) / max_samples, 1))

Average SD with n-1: 4.8
Average SD with n: 4.3

...and compare those values to the actual **Population Standard Deviation**...

In [53]:
round(pop_sd,1)

5.0

...and we see that, on average, when we have $n$ in the denominator, we underestimate the **Population Standard Deviation** more, than when we have $n-1$ in the denominator.